apiVersion: v1
clusters:
- cluster:
    certificate-authority-data: <ca-cert-data>
    server: <api-server-url>
  name: my-cluster
contexts:
- context:
    cluster: my-cluster
    user: <user-name>
  name: my-context
current-context: my-context
kind: Config
preferences: {}
users:
- name: <user-name>
  user:
    client-certificate-data: <user-cert-data>
    client-key-data: <user-key-data>
